{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeacle.prometheus.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubeacle.prometheus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    {{- include "kubeacle.prometheus.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
