{{- if and .Values.prometheus.enabled .Values.prometheus.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeacle.prometheus.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubeacle.prometheus.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.prometheus.persistence.accessMode | quote }}
  {{- if .Values.prometheus.persistence.storageClass }}
  storageClassName: {{ .Values.prometheus.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size | quote }}
{{- end }}
