{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeacle.prometheus.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubeacle.prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'rightsizer'
        static_configs:
          - targets: ['{{ include "kubeacle.backend.fullname" . }}:{{ .Values.backend.service.port }}']
        metrics_path: /metrics
        scrape_interval: {{ .Values.prometheus.scrapeInterval }}

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
{{- end }}
