{{- if .Values.prometheus.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeacle.prometheus.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubeacle.prometheus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubeacle.prometheus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeacle.prometheus.selectorLabels" . | nindent 8 }}
      {{- with .Values.prometheus.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "kubeacle.serviceAccountName" . }}
      {{- with .Values.prometheus.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: prometheus
          image: {{ include "kubeacle.prometheus.image" . }}
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          {{- with .Values.prometheus.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time={{ .Values.prometheus.retention }}"
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          {{- with .Values.prometheus.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
              readOnly: true
            - name: storage
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: {{ include "kubeacle.prometheus.fullname" . }}
        - name: storage
          {{- if .Values.prometheus.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "kubeacle.prometheus.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.prometheus.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prometheus.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prometheus.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
