FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o rightsizer ./cmd/server

FROM gcr.io/distroless/static-debian12
COPY --from=builder /app/rightsizer /rightsizer
EXPOSE 8080
ENTRYPOINT ["/rightsizer"]
